### ISSUE TITLE
Readme out-of-date

### ISSUE THREAD

**Issue by Aliance** [qiao/PathFinding.js#105]
[There](https://github.com/qiao/PathFinding.js/blob/master/README.md#basic-usage) was said that I can pass width/height OR matrix, but [here](https://github.com/qiao/PathFinding.js/blob/master/src/core/Grid.js#L12) I saw another: that w/h are required anyway.

Furthermore, I can not understand why sometimes x and y coordinates are mixed up: [here](https://github.com/qiao/PathFinding.js/blob/master/src/core/Grid.js#L84), [here](https://github.com/qiao/PathFinding.js/blob/master/src/core/Grid.js#L96), etc...

**Comment by qiao** [comment]
Hi @Aliance , on line 15 of https://github.com/qiao/PathFinding.js/blob/master/src/core/Grid.js#L15, there's a check for whether the first parameter is an array(typeof array is 'object') or not, if it's an array, then the width and height variable will be calculated from the array. So the width and height variable are actually optional.

The reason why the x and y are reversed is that the nodes are stored in a two dimensional array, which looks like 

```js
var matrix = [
  [A, B, D], 
  [E, F, G],
  [H, I, J]
]
```

if you want to get `H`, whose coordinate is `{x: 0, y: 2}`, then you have to write  `matrix[2][0]`, and you will see that it's actually `matrix[y][x]` instead of `matrix[x][y]`.
