### ISSUE TITLE
Pathfinding round grid

### ISSUE THREAD

**Issue by rohanabraham** [qiao/PathFinding.js#155]
The pathfinding library works great.

We need to be able to set the grid to be round (like the world is round), so point A to B might have a shorter way the path the other way.

What is the best way to achieve this?
![Example of Wrapped World](https://user-images.githubusercontent.com/4366633/37648369-aea32f6a-2c26-11e8-972e-207c79724eda.png)

**Comment by brean** [comment]
[Grid](https://github.com/qiao/PathFinding.js/blob/master/src/core/Grid.js#L144) has a getNeighbors function that gives you the next possible node while the algorithm searches the grid. You just need to extend this, so that if the next x value is -1 you set it to the grid width or if it is grid width + 1 you set it to 0. So this behaves like a cylinder. for a sphere you also need to check the y value.

**Comment by rohanabraham** [comment]
Simple idea and works great!
We wanted a cylinder type movement than a sphere and it seems to be working well on initial tests
